// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKq0FWqosq1nKZg_P60r4lRb4Yiv9HV_U',
    appId: '1:1065371829372:web:f12b638f4cf7ee9a14b5f9',
    messagingSenderId: '1065371829372',
    projectId: 'feed-app-49e74',
    authDomain: 'feed-app-49e74.firebaseapp.com',
    storageBucket: 'feed-app-49e74.firebasestorage.app',
    measurementId: 'G-4RYVMJFZXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtPjevVV06iABrNma_Nk52ZpXs3TLtdYY',
    appId: '1:1065371829372:android:05a7b8fbce811f0714b5f9',
    messagingSenderId: '1065371829372',
    projectId: 'feed-app-49e74',
    storageBucket: 'feed-app-49e74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUGe28WrK_k9vkMpm5QVCuEc7kXyi5NQ4',
    appId: '1:1065371829372:ios:f45f82094ea96b3114b5f9',
    messagingSenderId: '1065371829372',
    projectId: 'feed-app-49e74',
    storageBucket: 'feed-app-49e74.firebasestorage.app',
    iosBundleId: 'com.example.feedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUGe28WrK_k9vkMpm5QVCuEc7kXyi5NQ4',
    appId: '1:1065371829372:ios:f45f82094ea96b3114b5f9',
    messagingSenderId: '1065371829372',
    projectId: 'feed-app-49e74',
    storageBucket: 'feed-app-49e74.firebasestorage.app',
    iosBundleId: 'com.example.feedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKq0FWqosq1nKZg_P60r4lRb4Yiv9HV_U',
    appId: '1:1065371829372:web:df880f5df542232914b5f9',
    messagingSenderId: '1065371829372',
    projectId: 'feed-app-49e74',
    authDomain: 'feed-app-49e74.firebaseapp.com',
    storageBucket: 'feed-app-49e74.firebasestorage.app',
    measurementId: 'G-2NMQMWBNS7',
  );
}
